default:
  outputs:
    dev:
      account: <>
      database: dbt
      password: 
      role: accountadmin
      schema: dev
      threads: 1
      type: snowflake
      user: sprsag
      warehouse: compute_wh
    prod:
      account: <>
      database: dbt
      password: 
      role: accountadmin
      schema: prod
      threads: 1
      type: snowflake
      user: sprsag
      warehouse: compute_wh
  target: dev