name: 'loop'
version: '1.0.0'
config-version: 2
profile: 'loop'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  loop:
    +materialized: table
    ephemeral:
      +materialized: ephemeral
    aggs:
      +schema: aggs
    qb_views:
      +materialized: view
    shopify_archived:
      +schema: shopify_archived
    single_platform: 
      +schema: single_platform
    dw2:
      +schema: '2'
    finance_reports:
      +schema: finance_reports
