
name: 'brazilian_olist'
version: '1.0.0'
config-version: 2
profile: 'postgres'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  brazilian_olist:
    staging:
      +unlogged: true
      olist:
        tables:
          +materialized: table
        views:
          +materialized: view