name: 'coveo_dataset_playground'
version: '1.0.0'

config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'my-snowflake-db'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets: 
  - "target"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  coveo_dataset_playground:
    # Applies to all files under models/metaflow/
    metaflow:
      materialized: view
