default:
  outputs:
    dev:
      type: postgres
      threads: 2
      host: database-1.cy8ltogyfgas.us-east-1.rds.amazonaws.com
      port: 5432
      user: postgres
      pass: ""
      dbname: postgres
      schema: vehicle_trajectory
  target: dev
